services:
  postgres:
    image: postgres:16
    container_name: calendar_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calendar
    ports:
      - "5566:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
